// <auto-generated />
using System;
using DrugManagement.Core.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrugManagement.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030091716_AddDrugManagementEntities")]
    partial class AddDrugManagementEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrugManagement.Core.Model.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountLeftAbsolute")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("AmountLeftInPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("BoughtBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BoughtOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrugPackageSizeId")
                        .HasColumnType("integer");

                    b.Property<int>("MetadataId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OpenedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PalatableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PersonConcerned")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoughtBy");

                    b.HasIndex("DrugPackageSizeId");

                    b.HasIndex("MetadataId");

                    b.HasIndex("PersonConcerned");

                    b.HasIndex("ShopId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.DrugMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agreeability")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrugMetadata");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.DrugPackageSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BundleSize")
                        .HasColumnType("integer");

                    b.Property<string>("BundleType")
                        .HasColumnType("text");

                    b.Property<int>("DrugMetaDataId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrugMetaDataId");

                    b.ToTable("DrugPackageSizes");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Postalcode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.Drug", b =>
                {
                    b.HasOne("DrugManagement.Core.Model.Person", "BoughtByPerson")
                        .WithMany("DrugsBought")
                        .HasForeignKey("BoughtBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DrugManagement.Core.Model.DrugPackageSize", "DrugPackageSize")
                        .WithMany("Drugs")
                        .HasForeignKey("DrugPackageSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrugManagement.Core.Model.DrugMetadata", "Metadata")
                        .WithMany("Drugs")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrugManagement.Core.Model.Person", "PersonConcernedPerson")
                        .WithMany("DrugsConcerned")
                        .HasForeignKey("PersonConcerned")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DrugManagement.Core.Model.Shop", "Shop")
                        .WithMany("Drugs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoughtByPerson");

                    b.Navigation("DrugPackageSize");

                    b.Navigation("Metadata");

                    b.Navigation("PersonConcernedPerson");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.DrugPackageSize", b =>
                {
                    b.HasOne("DrugManagement.Core.Model.DrugMetadata", "DrugMetadata")
                        .WithMany("PackageSizes")
                        .HasForeignKey("DrugMetaDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrugMetadata");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.DrugMetadata", b =>
                {
                    b.Navigation("Drugs");

                    b.Navigation("PackageSizes");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.DrugPackageSize", b =>
                {
                    b.Navigation("Drugs");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.Person", b =>
                {
                    b.Navigation("DrugsBought");

                    b.Navigation("DrugsConcerned");
                });

            modelBuilder.Entity("DrugManagement.Core.Model.Shop", b =>
                {
                    b.Navigation("Drugs");
                });
#pragma warning restore 612, 618
        }
    }
}
